-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 15:33:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema market9501
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema market9501
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `market9501` DEFAULT CHARACTER SET utf8 ;
USE `market9501` ;

-- -----------------------------------------------------
-- Table `market9501`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market9501`.`authors` (
  `idAuthors` INT NOT NULL AUTO_INCREMENT,
  `SecondName` VARCHAR(50) NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `Country` VARCHAR(50) NOT NULL DEFAULT 'Россия',
  PRIMARY KEY (`idAuthors`),
  UNIQUE INDEX `FullName` (`SecondName` ASC, `FirstName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `market9501`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market9501`.`books` (
  `idBooks` INT NOT NULL AUTO_INCREMENT,
  `idAuthors` INT NOT NULL,
  `bookTitle` VARCHAR(50) NOT NULL,
  `genre` ENUM('проза', 'поэзия', 'другое') NOT NULL DEFAULT 'проза',
  `price` DECIMAL(6,2) NOT NULL DEFAULT '0.00',
  `mass` DECIMAL(4,3) NOT NULL DEFAULT '0.000',
  `pages` SMALLINT NOT NULL DEFAULT '0',
  `year` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`idBooks`),
  INDEX `fk_Books_Authors1_idx` (`idAuthors` ASC) VISIBLE,
  CONSTRAINT `fk_Books_Authors1`
    FOREIGN KEY (`idAuthors`)
    REFERENCES `market9501`.`authors` (`idAuthors`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `market9501`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market9501`.`customers` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `market9501`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market9501`.`orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NOT NULL,
  `orderDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Customers1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `market9501`.`customers` (`idCustomer`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `market9501`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market9501`.`content` (
  `idOrders` INT NOT NULL,
  `idBooks` INT NOT NULL,
  `quantity` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idOrders`, `idBooks`),
  INDEX `fk_Orders_has_Books_Books1_idx` (`idBooks` ASC) VISIBLE,
  INDEX `fk_Orders_has_Books_Orders_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_has_Books_Books1`
    FOREIGN KEY (`idBooks`)
    REFERENCES `market9501`.`books` (`idBooks`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orders_has_Books_Orders`
    FOREIGN KEY (`idOrders`)
    REFERENCES `market9501`.`orders` (`idOrders`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
